heat_template_version: 2015-04-30

description: Template to deploy IPFE

parameters:

  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    constraints:
      - custom_constraint: nova.flavor    
  availability_zone:
    type: string
    description: Name of AZ.   
  network_control:
    type: string
    label: Network
    description: Network to be used for Management
    constraints:
      - custom_constraint: neutron.network
  network_qinq:
    type: string
    label: Network
    description: Network to be used for QinQ
    constraints:
      - custom_constraint: neutron.network      
  network_interconnect:
    type: string
    label: Network
    description: Network to be used for Interconnect
    constraints:
      - custom_constraint: neutron.network
  network_lac:
    type: string
    label: Network
    description: Network to be used for L2TP Access Concentrator
    constraints:
      - custom_constraint: neutron.network
      
resources:

  port_control:
    type: OS::Neutron::Port
    properties:    
      network: { get_param: network_control }
      
  port_qinq:
    type: OS::Neutron::Port
    properties:    
      network: { get_param: network_qinq }      
        
  port_interconnect:
    type: OS::Neutron::Port
    properties:    
      network: { get_param: network_interconnect }        
        
  port_lac:
    type: OS::Neutron::Port
    properties:    
      network: { get_param: network_lac }        
        
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      flavor_update_policy: RESIZE
      availability_zone: { get_param: availability_zone }
      networks:
        - port: { get_resource: port_control }
        - port: { get_resource: port_qinq }        
        - port: { get_resource: port_interconnect }
        - port: { get_resource: port_lac }
        
outputs:
  name:
    description: Name of the server instance.
    value: { get_attr: [server, name] }
  ip:
    description: The IP address of the instance.
    value: { get_attr: [server, first_address] }
  port:
    description: The network port of the server instance.
    value: { get_resource: port1 } 
  server_id:
    description: get uuid of server resource
    value: { get_resource: server }
