heat_template_version: 2015-04-30

description: Template to deploy Virtual Network

parameters:

  name:    
    type: string
  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix:    
    type: string
  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len:    
    type: string
  network_ipam_refs:
    type: string  
    default: "default-domain:default-project:default-network-ipam"
  virtual_network_properties_allow_transit:
    type: boolean
    default: False 
  virtual_network_properties_forwarding_mode:
    type: string
    constraints:
      - allowed_values: [l2_l3, l2, l3]
    default: "l2_l3"
  virtual_network_properties_rpf:
    type: string
    constraints:
      - allowed_values: [enable, disable]
    default: "disable"
  routes:    
    type: json
    default: []
    
resources: 

  route_table:
    type: OS::ContrailV2::RouteTable
    properties:
      name:         
        str_replace:
          template: $name_routes
          params:
           $name: { get_param: name }
      routes:
        routes_route: { get_param: routes }     

  virtual_network:
    depends_on: [ route_table ]  
    type: OS::ContrailV2::VirtualNetwork  
    properties:
      name: { get_param: name }
      network_ipam_refs: [{ get_param: network_ipam_refs }]
      route_table_refs: [{ get_resource: route_table }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: { get_param: network_ipam_refs_data_ipam_subnets_subnet_ip_prefix },
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: { get_param: network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len },
                },
            }]
         }]
      virtual_network_properties:
        virtual_network_properties_allow_transit: { get_param: virtual_network_properties_allow_transit }
        virtual_network_properties_forwarding_mode: { get_param: virtual_network_properties_forwarding_mode }
        virtual_network_properties_rpf: { get_param: virtual_network_properties_rpf }
        
outputs:
  virtual_network_show:
    value: {get_attr: [virtual_network, show]}
  route_table_show:
    value: {get_attr: [route_table, show]}