heat_template_version: 2015-04-30

description: Template to deploy VM

parameters:

  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    constraints:
      - custom_constraint: glance.image
  instance_type:
    type: string
    label: Instance Type
    description: Type of instance (flavor) to be used
    constraints:
      - custom_constraint: nova.flavor    
  availability_zone:
    type: string
    description: Name of AZ.   
  networks:
    type: json
    label: Networks and IPs
    description: Networks to be used for Management
      
resources:
       
  server:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      flavor_update_policy: RESIZE
      availability_zone: { get_param: availability_zone }    
      networks: { get_param: networks }
 
outputs:
  show:
    value: {get_attr: [server, show]}